steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/estimagent/api-v2', '-f', 'Dockerfile.api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/estimagent/api-v2']

images:
  - 'gcr.io/estimagent/api-v2'
